# Generated by Django 3.2.5 on 2021-08-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=30)),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('phone', models.IntegerField(max_length=10)),
                ('birthday', models.DateField()),
                ('project', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('image', models.ImageField(upload_to='images')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='etmapp.role')),
            ],
        ),
    ]
