# Generated by Django 3.2.5 on 2021-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
