# Generated by Django 3.2.5 on 2021-08-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0004_alter_userdata_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='project',
            new_name='assigned_project',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=30)),
                ('project_name', models.CharField(max_length=30)),
                ('project_detail', models.TextField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='etmapp.userdata')),
            ],
        ),
    ]
