# Generated by Django 3.2.5 on 2021-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0005_auto_20210818_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(default=''),
        ),
        # migrations.AddField(
        #     model_name='project',
        #     name='deadline',
        #     field=models.DateField(default=''),
        # ),
        migrations.AddField(
            model_name='project',
            name='docx',
            field=models.TextField(default=''),
        ),
        # migrations.AddField(
        #     model_name='project',
        #     name='start_date',
        #     field=models.DateField(default=''),
        # ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_detail',
            field=models.TextField(default=''),
        ),
    ]
