# Generated by Django 3.2.5 on 2021-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0006_auto_20210818_2114'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='project',
        #     name='deadline',
        #     field=models.DateField(auto_now_add=True),
        # ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='start_date',
        #     field=models.DateField(auto_now_add=True),
        # ),
    ]
