# Generated by Django 3.2.5 on 2021-08-18 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0008_auto_20210818_2116'),
    ]

    operations = [
    #     migrations.AddField(
    #         model_name='project',
    #         name='deadline',
    #         field=models.DateField(default=datetime.date(2021, 8, 18)),
    #     ),
    #     migrations.AddField(
    #         model_name='project',
    #         name='start_date',
    #         field=models.DateField(default=datetime.date(2021, 8, 18)),
    #     ),
    ]
