# Generated by Django 3.2.5 on 2021-08-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0009_auto_20210818_2121'),
    ]

    operations = [
    #     migrations.RemoveField(
    #         model_name='project',
    #         name='deadline',
    #     ),
    #     migrations.RemoveField(
    #         model_name='project',
    #         name='start_date',
    #     ),
    ]
