# Generated by Django 3.2.5 on 2021-08-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0012_auto_20210818_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='assigned_project',
            field=models.CharField(default='', max_length=50),
        ),
    ]
