# Generated by Django 3.2.5 on 2021-08-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0013_alter_userdata_assigned_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
    ]
