# Generated by Django 3.2.5 on 2021-08-19 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0014_remove_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.date(2021, 8, 19)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 8, 19)),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('docx', models.TextField()),
                ('task_start', models.DateTimeField(default=datetime.date(2021, 8, 19))),
                ('task_deadline', models.DateTimeField(default=datetime.date(2021, 8, 19))),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='etmapp.userdata')),
                ('task_of', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='etmapp.project')),
            ],
        ),
    ]
