# Generated by Django 3.2.5 on 2021-08-19 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0015_auto_20210819_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(default=datetime.date(2021, 8, 19)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start',
            field=models.DateField(default=datetime.date(2021, 8, 19)),
        ),
    ]
