# Generated by Django 3.2.5 on 2021-08-22 17:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etmapp', '0017_auto_20210822_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtdUser',
            new_name='UserProfile',
        ),
    ]
