# Generated by Django 3.2.5 on 2021-08-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etmapp', '0019_auto_20210822_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
